language: "python"
services:
  - postgresql
env:
  - 'DJANGO=3.0 DB=postgresql'
install:
  - 'pip install -r requirements/requirements.txt'
before_script:
  - 'python manage.py makemigrations'
  - 'python manage.py migrate'
script:
  - 'python manage.py test'
