# Generated by Django 3.0.1 on 2019-12-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data_publicacao',
            field=models.DateTimeField(auto_now=True, db_column='dt_publicacao'),
        ),
    ]
