# Generated by Django 3.0.1 on 2020-01-14 03:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20200103_0208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('codigo', models.UUIDField(db_column='cd_categoria', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='nm_categoria', max_length=100, unique=True)),
                ('descricao', models.CharField(db_column='ds_categoria', max_length=300, unique=True)),
            ],
            options={
                'db_table': 'tb_categoria',
            },
        ),
        migrations.CreateModel(
            name='PostTag',
            fields=[
                ('codigo', models.UUIDField(db_column='cd_post_tag', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('post', models.ForeignKey(db_column='fk_post', on_delete=django.db.models.deletion.DO_NOTHING, to='post.Post')),
            ],
            options={
                'db_table': 'tb_post_tag',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('codigo', models.UUIDField(db_column='cd_categoria', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='ds_tag', max_length=100, unique=True)),
                ('posts', models.ManyToManyField(through='post.PostTag', to='post.Post')),
            ],
            options={
                'db_table': 'tb_tag',
            },
        ),
        migrations.AddField(
            model_name='posttag',
            name='tag',
            field=models.ForeignKey(db_column='fk_tag', on_delete=django.db.models.deletion.DO_NOTHING, to='post.Tag'),
        ),
        migrations.CreateModel(
            name='PostCategoria',
            fields=[
                ('codigo', models.UUIDField(db_column='cd_post_categoria', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('categoria', models.ForeignKey(db_column='fk_categoria', on_delete=django.db.models.deletion.DO_NOTHING, to='post.Categoria')),
                ('post', models.ForeignKey(db_column='fk_post', on_delete=django.db.models.deletion.DO_NOTHING, to='post.Post')),
            ],
            options={
                'db_table': 'tb_post_categoria',
            },
        ),
        migrations.AddField(
            model_name='categoria',
            name='posts',
            field=models.ManyToManyField(through='post.PostCategoria', to='post.Post'),
        ),
    ]
