# Generated by Django 3.0.1 on 2020-01-23 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20200114_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='descricao',
            field=models.CharField(db_column='ds_categoria', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='nome',
            field=models.CharField(db_column='ds_tag', max_length=100),
        ),
    ]
