-- MySQL Script generated by MySQL Workbench
-- sáb 17 nov 2018 01:40:53 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `Account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Account` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Account` (
  `id` INT NOT NULL,
  `email` VARCHAR(66) NOT NULL,
  `password` TEXT NOT NULL,
  `dateRegistration` DATETIME NOT NULL,
  `lastAccess` DATETIME NOT NULL,
  `lastAccessLocation` VARCHAR(99) NULL,
  `isAdmin` TINYINT(1) NOT NULL DEFAULT 0,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `EMAIL_UNIQUE` ON `Account` (`email` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Author`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Author` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Author` (
  `id` INT NOT NULL,
  `idAccount` INT NOT NULL,
  `nickname` VARCHAR(33) NOT NULL,
  `name` VARCHAR(63) NOT NULL,
  `fullName` VARCHAR(77) NOT NULL,
  `photo` BLOB NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `NICKNAME_UNIQUE` ON `Author` (`nickname` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Post` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Post` (
  `id` INT NOT NULL,
  `idAuthor` INT NOT NULL,
  `title` VARCHAR(99) NOT NULL,
  `description` VARCHAR(333) NOT NULL,
  `content` TEXT NOT NULL,
  `note` VARCHAR(333) NULL,
  `datePublication` DATETIME NOT NULL,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Category` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Category` (
  `id` INT NOT NULL,
  `idAuthor` INT NOT NULL,
  `name` VARCHAR(99) NOT NULL,
  `description` VARCHAR(333) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `NAME_UNIQUE` ON `Category` (`name` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Tag` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Tag` (
  `id` INT NOT NULL,
  `idAuthor` INT NOT NULL,
  `name` VARCHAR(99) NOT NULL,
  `description` VARCHAR(333) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `NAME_UNIQUE` ON `Tag` (`name` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Responsible`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Responsible` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Responsible` (
  `id` INT NOT NULL,
  `name` VARCHAR(63) NOT NULL,
  `email` VARCHAR(66) NOT NULL,
  `phone` VARCHAR(16) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `EMAIL_UNIQUE` ON `Responsible` (`email` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `PostComment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PostComment` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `PostComment` (
  `id` INT NOT NULL,
  `idPost` INT NOT NULL,
  `idResponsible` INT NOT NULL,
  `title` VARCHAR(33) NOT NULL,
  `comment` TEXT NOT NULL,
  `dateComment` DATETIME NOT NULL,
  `isPublic` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `PostHasTag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PostHasTag` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `PostHasTag` (
  `idPost` INT NOT NULL,
  `idTag` INT NOT NULL,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`idPost`, `idTag`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `PostHasCategory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PostHasCategory` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `PostHasCategory` (
  `idPost` INT NOT NULL,
  `idCategory` INT NOT NULL,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`idPost`, `idCategory`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
